---
- name: Include global vars
  include_vars:
    file: vars/main.yml

- name: Create my user
  user:
    name: "{{ user_group }}"
    password: "{{ userpw | string | password_hash('sha512') }}"
    comment: "{{ fullname }}"
    shell: /usr/bin/zsh
    home: "/home/{{ user_group }}"
    uid: 1000
    group: 1000
    groups: wheel,plugdev,docker
    update_password: on_create

- name: Docker user
  user:
    name: docker
    shell: /usr/bin/bash
    uid: 500
    group: 500
