---
- name: Install DNF packages
  dnf:
    name:
      - gcc
      - python-devel
      - openssl-devel
      - openssl
      - perl-JSON
      - python-netaddr
      - sshpass
      - power-profiles-daemon
      - libva-utils
      - libva
      - ffmpeg
      - gstreamer1-plugins-base
      - gstreamer1-plugins-bad-*
      - gstreamer1-plugins-good-*
      - gstreamer1-plugin-openh264
      - gstreamer1-libav
      - gstreamer1-vaapi
      - lame*
      - intel-media-driver
      - kernel-devel
      - kernel-headers
      - openrazer-meta
      - polychromatic
      - kernel-devel
      - teams
      - libnsl
      - htop
      - snapper
      - python3-dnf-plugin-snapper
      - nmap
      - dnf-plugin-tracer
      - dnf-plugins-core
      - python-dnf
      - golang
      - vault
      - terraform
      - vagrant
      - consul
      - packer
      - libatomic
      - obs-studio
      - keybase
      - slack
      - pv
      - zstd
      - rclone
      - remmina
      - gh
      - code
      - vim
      - google-chrome-stable
      - brave-browser
      - zsh
      - insync
      - zerotier-one
      - powershell
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - containerd.io
      - libvirt-client
      - gnome-network-displays
      - wavemon
      - firewall-config
    exclude:
      - gstreamer1-plugins-bad-free-devel
      - lame-devel
    state: present
