---
- name: Install Flatpak Packages
  flatpak:
    name:
      - org.signal.Signal
      - org.gnome.Extensions
      - com.discordapp.Discord
      - com.bitwarden.desktop
      - com.getpostman.Postman
    state: present
