---
- name: Update DNF packages
  dnf:
    name: "*"
    state: latest

- name: Update Flatpak packages
  command: /usr/bin/flatpak update --noninteractive
  register: flatpak_check
  changed_when: "flatpak_check.rc != 0"
