---
- name: Update DNF packages
  dnf:
    name: "*"
    state: latest

- name: Check Flatpak packages
  command: /usr/bin/flatpak update --noninteractive --no-deploy
  register: flatpak_check

- name: Flatpak Result
  debug:
    msg: "{{ flatpak_check.stdout }}"

- name: Update Flatpak packages
  command: /usr/bin/flatpak update --noninteractive
  when: flatpak_check.stdout != "Nothing to do."
